name: "[CLI] Release"

on:
  repository_dispatch:
    types: [ release ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          tag: ${{ github.event.client_payload.VERSION }}
          name: Release ${{ github.event.client_payload.VERSION }}
          body: |
            Release ${{ github.event.client_payload.VERSION }}
      - name: Write Upload URL To File
        run: |
          echo "${{steps.create_release.outputs.upload_url}}" > upload_url.txt
      - name: Publish Upload URL
        uses: actions/upload-artifact@v3.1.3
        with:
          name: upload_url.txt
          path: upload_url.txt

  release:
    needs: setup
    strategy:
      matrix:
        os:
          - ubuntu-latest
#          - macos-latest
#          - macos-latest-xlarge
        include:
          - os: ubuntu-latest
            label: linux
#          - os: macos-latest
#            label: mac
#          - os: macos-latest-xlarge
#            label: mac-m1
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./gradlew nativeCompile
      - name: Get Release URL
        uses: actions/download-artifact@v3.0.2
        with:
          name: upload_url.txt
      - name: Get Upload URL
        run: |
          echo "UPLOAD_URL=$(cat upload_url.txt)" >> $GITHUB_ENV
      - name: Publish Native Image
        if: success()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: rebackupable-${{ github.event.client_payload.VERSION }}-${{matrix.label}}
          path: build/native/nativeCompile/rebackupable
      - name: Release Native Image Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          upload_url: ${{env.UPLOAD_URL}}
          asset_name: rebackupable-${{ github.event.client_payload.VERSION }}-${{matrix.label}}
          asset_path: build/native/nativeCompile/rebackupable
          asset_content_type: application/octet-stream
