name: "[CLI] Release"

on:
  repository_dispatch:
    types: [ release ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          tag: ${{ github.event.client_payload.VERSION }}
          name: Release ${{ github.event.client_payload.VERSION }}
          body: |
            Release ${{ github.event.client_payload.VERSION }}
      - name: Write Upload URL To File
        run: |
          echo "${{steps.create_release.outputs.upload_url}}" > upload_url.txt
      - name: Publish Upload URL
        uses: actions/upload-artifact@v4.3.1
        with:
          name: upload_url.txt
          path: upload_url.txt

  release:
    needs: setup
    strategy:
      matrix:
        os:
#          - ubuntu-latest
          - macos-13-large
          - macos-13-xlarge
        include:
#          - os: ubuntu-latest
#            label: linux
          - os: macos-13-large
            label: macos-x86_64
          - os: macos-13-xlarge
            label: macos-arm64
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1.2.1
        with:
          java-version: "21"
          distribution: "graalvm"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "22.3.0"
      - name: Build
        run: ./gradlew nativeCompile osxApp
      - name: Get Release URL
        uses: actions/download-artifact@v4.1.4
        with:
          name: upload_url.txt
      - name: Get Upload URL
        run: |
          echo "UPLOAD_URL=$(cat upload_url.txt)" >> $GITHUB_ENV
      - name: Create the DMG
        run: |
          hdiutil create -volname "Rebackupable" -srcfolder build/app/Rebackupable.app -ov -format UDZO Rebackupable-${{matrix.label}}.dmg
      - name: Upload DMG to release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          upload_url: ${{env.UPLOAD_URL}}
          asset_name: Rebackupable-${{matrix.label}}.dmg
          asset_path: Rebackupable-${{matrix.label}}.dmg
          asset_content_type: application/octet-stream
